FLAGS = -O3 -std=c++17
TARGETS = test1 test2 test3 test4 test5 test6 test7 meshTest

all: $(TARGETS)

test1:
	g++ $(FLAGS) test1.cpp -o test1

test2:
	g++ $(FLAGS) test2.cpp -o test2

test3:
	g++ $(FLAGS) test3.cpp -o test3

test4:
	g++ $(FLAGS) test4.cpp -o test4

test5:
	g++ $(FLAGS) test5.cpp -o test5

test6:
	g++ $(FLAGS) test6.cpp -o test6

test7:
	g++ $(FLAGS) test7.cpp -o test7

meshTest:
	g++ $(FLAGS) meshTest.cpp -o meshTest

clean:
	rm test1
	rm test2
	rm test3
	rm test4
	rm test5
	rm test6
	rm test7
	rm meshTest
